# Plex server details
# * Defaults to plexapi config
plex:
    baseurl: 'PLEX_BASE_URL' # fallback http://localhost:32400
    token: 'PLEX_TOKEN'  # https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

# trakt.tv API details
# * Required for fetching trakt lists
# Create a Trakt.tv account, then create an API app here:
# https://trakt.tv/oauth/applications/new
trakt:
    username: 'TRAKT_USERNAME'
    client_id: 'TRAKT_CLIENT_ID'
    client_secret: 'TRAKT_SECRET'
    oauth_token: ''  # Filled in later depending on recipe

# The Movie Database details
# * Required for fetching scores, release dates etc for weighted sorting
# * Required for matching any library items that use the TMDb agent with the items from the lists
#   (if those items do not include a TMDb ID)
tmdb:
    api_key: 'TMDB_API_KEY'
    cache_file: '/tmp/tmdb_details.shelve'

# TheTVDB details
# * Required for matching any library items that use the TheTVDB agent with the items from the lists
#   (if those items do not include a TheTVDB ID)
tvdb:
    username: 'TVDB_USERNAME'
    api_key: 'TVDB_API_KEY'
    user_key: 'TVDB_USER_KEY'
